#!/bin/sh

export FILE_SERVER_MAJOR_VERSION=1.0
export FILE_SERVER_VERSION=${FILE_SERVER_MAJOR_VERSION}.0
export FILE_CLIENT_MAJOR_VERSION=1.0
export FILE_CLIENT_VERSION=${FILE_CLIENT_MAJOR_VERSION}.0
export REPO=eluinstra/
