#!/bin/sh

export FILE_SERVER_MAJOR_VERSION=2.0
export FILE_SERVER_VERSION=${FILE_SERVER_MAJOR_VERSION}.0-M1
export FILE_CLIENT_MAJOR_VERSION=2.0
export FILE_CLIENT_VERSION=${FILE_CLIENT_MAJOR_VERSION}.0-M1
export REPO=eluinstra/
