#!/bin/sh

export FILE_SERVER_MAJOR_VERSION=2.1
export FILE_SERVER_VERSION=${FILE_SERVER_MAJOR_VERSION}.1

export FILE_CLIENT_MAJOR_VERSION=2.1
export FILE_CLIENT_VERSION=${FILE_CLIENT_MAJOR_VERSION}.1

export POSTGRES_DRIVER_VERSION=42.7.7
export POSTGRES_DRIVER=postgresql-${POSTGRES_DRIVER_VERSION}.jar
export FLYWAY_DRIVER_NAME=flyway-database-postgresql
export FLYWAY_DRIVER_VERSION=12.4.0
export FLYWAY_DRIVER=${FLYWAY_DRIVER_NAME}-${FLYWAY_DRIVER_VERSION}.jar

export REPO=eluinstra/
export IMAGE_NAMES="file-server-bin file-client-bin file-server-pg file-client-pg"
